# Generated by Django 3.2.5 on 2022-12-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20221222_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Toss'), (1, 'Nuggets'), (2, 'Menu (cordon bleu)'), (3, 'Menu (cordon rouge)'), (4, "L'addition"), (5, 'Burger de la mort')], default=1, help_text="Veuillez sélectionner l'écran qui compose votre boîte", verbose_name='Type de carte'),
        ),
    ]
