# Generated by Django 3.2.5 on 2022-12-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_deck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name': 'Paquet de cartes', 'verbose_name_plural': 'Paquets de cartes'},
        ),
        migrations.AddField(
            model_name='card',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Cette carte sera partagée en ligne'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Toss'), (1, 'Nuggets'), (2, 'Menu (cordon bleu)'), (3, 'Menu (cordon rouge)'), (4, "L'addition"), (5, 'Burger de la mort')], default=1, verbose_name='Type de carte'),
        ),
    ]
