# Generated by Django 3.2.5 on 2022-12-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20221223_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Carte publique ?'),
        ),
    ]
