# Generated by Django 3.2.5 on 2022-12-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20221223_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Toss'), (1, 'Nuggets'), (2, 'Sel ou poivre'), (3, 'Menu (cordon bleu)'), (4, 'Menu (cordon rouge)'), (5, "L'addition"), (6, 'Burger de la mort')], default=1, verbose_name='Type de carte'),
        ),
    ]
