# Generated by Django 3.2.5 on 2022-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cards.Tag'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(blank=True, to='cards.Card'),
        ),
    ]
