# Generated by Django 3.2.5 on 2022-12-30 17:07

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20221227_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=markdownfield.models.MarkdownField(default='Tapez le texte de votre carte (en utilisant markdown)', rendered_field='text_rendered', verbose_name='Texte de la carte'),
        ),
    ]
