# Generated by Django 3.2.5 on 2022-12-30 17:08

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=markdownfield.models.MarkdownField(default='Tapez le texte de votre carte (en utilisant **Markdown**)', rendered_field='text_rendered', verbose_name='Texte de la carte'),
        ),
    ]
